### ISSUE TITLE
How do I specify query options with mapRecordsToProps?

### ISSUE THREAD

**Issue by NullVoxPopuli** [exivity/react-orbitjs#10]
the docs seem to only say that I can specify the first parameter to `queryStore` by passing a mapRecordsToProps.

What I'm wanting to do is something like this:

![image](https://user-images.githubusercontent.com/199018/42952610-db2b720c-8b46-11e8-8bf9-65d6345946ff.png)

but I'd like to be able to utilize `withData` so I don't need to write all that prop/change logic over again, ya know?

**Comment by hongaar** [comment]
I'm not sure what you're trying to achieve. Maybe you can simply omit the sort/filter options in the `queryStore` call, and only use them in your `mapRecordsToProps` function?

**Comment by NullVoxPopuli** [comment]
the options I don't know how how to pass in mapRecordsToProps are the second parameter to queryStore (the label, sources, etc) http://orbitjs.com/v0.15/guide/querying-data.html#Query-options

**Comment by hongaar** [comment]
Ah! `mapRecordsToProps` uses `store.cache.query` which doesn't have a query options parameter.

**Comment by NullVoxPopuli** [comment]
ah ok, so what I'd want to do, is continue what I'm doing above, and then also have a mapRecordsToProps to catch the cached version, and then on the next re-render of the component, because I'd see the cached version, I'd not call `fetchData` (as I have defined above)

**Comment by NullVoxPopuli** [comment]
would my `mapRecordsToProps` have the same chained `findRecords` call?

**Comment by hongaar** [comment]
Yes. But as I said, you could as well remove them from the `queryStore` call in your `fetchData` function. They'll be filtered and sorted in the `mapRecordsToProps` function anyway.

**Comment by NullVoxPopuli** [comment]
well, I still need them for the initial call to the remote api, yeah?

**Comment by hongaar** [comment]
Depends on what external store you're using. I'm not 100% sure, but I guess filtering / sorting is applied after a request to your API has been made, meaning it's done in Orbit. In that case it would be redundant.

**Comment by NullVoxPopuli** [comment]
this is what I have so far:

```ts
import * as React from 'react';
import { withData as withOrbit, WithDataProps } from 'react-orbitjs';

import { TYPE_NAME } from '@data/models/project';

function mapRecordsToProps(passedProps) {
  const {
    sortProperty, defaultSort,
    filterOptions, pageOptions
  } = passedProps;

  return {
    fromCache: q =>
      q.findRecords(TYPE_NAME)
       .sort(sortProperty || defaultSort)
       .filter(filterOptions || [])
       .page({ offset: 0, limit: 20, ...( pageOptions || {} ) })
  };
}

// http://orbitjs.com/v0.15/guide/querying-data.html
export function withData(WrappedComponent) {
  class DataWrapper extends React.Component {
    state = {};

    fetchData = async (this: WrappedComponent) => {
      const {
        queryStore,
        sortProperty, defaultSort,
        filterOptions, pageOptions
      } = this.props;

      const records = await queryStore(
        q => (
          q.findRecords(TYPE_NAME)
           .sort(sortProperty || defaultSort)
           .filter(filterOptions || [])
           .page({ offset: 0, limit: 20, ...( pageOptions || {} ) })
        ), {
          label: `Query Projects`,
          sources: {
            remote: {
              include: ['products', 'organization']
            }
          }
        }
      );

      this.setState({ fromNetwork: records });
    }

    render() {
      const { fromNetwork } = this.state;
      const { fromCache } = this.props;

      if (!fromCache) this.fetchData();

      const dataProps = {
        projects: fromCache || fromNetwork,
        isLoading: !fromNetwork || fromNetwork.length === 0
      };

      return (
        <WrappedComponent
          { ...dataProps }
          { ...this.props }
        />
      );
    }
  }

  return withOrbit(mapRecordsToProps)(DataWrapper)
}
```
(still a work in progress, (I keep getting pulled away from working on this, and it's not yet making the network request))

my external store is a JsonApiSource.
filtering / sorting should happen on the backend due to request params, yeah?

**Comment by hongaar** [comment]
> filtering / sorting should happen on the backend due to request params, yeah?

Not totally sure about this. But you'll be able to quickly figure this out by monitoring the network request

> and it's not yet making the network request

Becuase your `fromCache` prop uses `findRecords` it will be set to an empty array when there's no data (yet), so `!fromCache` will actually evaluate to false.
