### ISSUE TITLE
withData is not rerendered after a replaceRelatedRecord operation with null

### ISSUE THREAD

**Issue by julfla** [exivity/react-orbitjs#12]
Hi,

I have been using react-orbitjs for a couple of days now, I really like it's simplicity! :+1: 

It seems that withData component is not receiving updates when replacing a related record by null:

``` javascript
store.update(t => t.replaceRelatedRecord(
  {type: "todo", id: "my-first-todo"},
   "owner",
   null,
))
```

I've opened PR #11 with a new test case, and what could a fix.

Hope it can be of any help :slightly_smiling_face:

**Comment by hongaar** [comment]
Merged. Nice catch, thanks for the PR!
