### ISSUE TITLE
How do you do a proper network-first then cache approach?

### ISSUE THREAD

**Issue by NullVoxPopuli** [exivity/react-orbitjs#14]
So, in my app, I have a `WithCurrentUser` HOC that I use it many places per page.
they way I have it implemented at the moment causes a request per usage.
I know this is a concurrency ( / a lack of concurrency handling) issue, but I'm just wondering what this library, and/or orbit + @dgeb recommend for this kind of behavior.

Thanks!

Things I have currently:
 - [The Orbit.js Configuration for the Project :tm:](https://github.com/sillsdev/appbuilder-portal/blob/master/source/SIL.AppBuilder.Portal.Frontend/src/data/store.ts#L57)
 - general `query` (similar to `withData`, but causes a network request: https://github.com/sillsdev/appbuilder-portal/blob/master/source/SIL.AppBuilder.Portal.Frontend/src/data/query.tsx (unsure how to cache these, and at what layer caching should happen, (in the component, orbit, etc)

 - withCurrentUser (uses fetch, cause I couldn't figure out how to get orbit to make a one-off request to a custom endpoint on my users controller) https://github.com/sillsdev/appbuilder-portal/blob/master/source/SIL.AppBuilder.Portal.Frontend/src/data/with-current-user.tsx

**Comment by hongaar** [comment]
Generally speaking, this project makes no special assumptions about any business logic which controls when to use live queries / when to use the cache.
But Orbit.js probably supports this by implementing a custom request strategy in Orbit to achieve some form of automatic cache fallback after a first live query.

**Comment by NullVoxPopuli** [comment]
I just think that any library that integrates with orbit.js should also provide common network/cache strategies, but I think they are too complicated for the average user, and it ends up with a lot of duplication between projects :-\

**Comment by hongaar** [comment]
I agree that those strategies can be difficult to fully understand and properly implement. But I don't believe this responsibility fits the goal of this project very well.

**Comment by NullVoxPopuli** [comment]
Well, it's my mission to take away the hard monotonous problems away from users. fwiw, it's a goal of the ember library to provide some default strategies: https://github.com/orbitjs/ember-orbit (there aren't any yet, but just need to make a PR to it).

I just don't think it's the users responsibility to re-invent the wheel between every project. :-\

**Comment by hongaar** [comment]
Agreed. How does ember-orbit plan to help you with this?

I just think server/local caching strategies are not bound to the React (or Ember for that matter) world; hence I don't think this is the right project.

**Comment by NullVoxPopuli** [comment]
> Agreed. I just think server/local caching strategies are not bound to the React (or Ember for that matter) world; hence I don't think this is the right project.

ah! so you're thinking maybe a separate package `orbit-default-strategies` or something. I could get behind that.

> How does ember-orbit plan to help you with this?

how do you mean? I just remember in the orbit gitter, @dgeb said that he'd like there to exist a set of default strategies

**Comment by hongaar** [comment]
> how do you mean? I just remember in the orbit gitter, @dgeb said that he'd like there to exist a set of default strategies

I was curious on how they will implement that. If it'd be some off-the-shelve configuration you can use or copy, or some helper functions to abstract aspects of the setting up of sources/coordinators.

> ah! so you're thinking maybe a separate package orbit-default-strategies or something. I could get behind that.

Maybe. Though I feel that maybe this 'problem' may as well be solved with more sample code for common use cases on the Orbit website.

What do you think this new repo should contain? Working code you can import, or sample code?

**Comment by NullVoxPopuli** [comment]
> What do you think this new repo should contain? Working code you can import, or sample code?

I think it's far too complicated to just provide sample code, so it neeeeeeds to be code you can import.
for example, for remote-controlled Ids, I need a ton of helpers to make sure I'm interoping betwiing local and remote ids properly
