### ISSUE TITLE
Silently fail when removing record

### ISSUE THREAD

**Issue by maksimsemenov** [exivity/react-orbitjs#17]
I have an issue when `withData` does not update props if I remove a record.

I think that the problem is in `handleTransform` function:
```
case 'removeRecord':
    // If the removed record had some relationships, inverse relationships
    // are modified too. As operation.record does not contain any relationships
    // we have to assume that all its inverse relationships defined
    // in the schema could be impacted and must be added to operationModels.
    operationModels.push(operation.record.type)
    const relationships = this.dataStore.schema.models[operation.record.type].relationships

    Object.keys(relationships)
      .map(k => relationships[k])
      .forEach(relationship => {
         console.log('withData-handleTransform-removeRecord', relationships)
         operationModels.push(relationship.model)
       })
    break
```

In case `relationships` is undefined it just silently falls and don't call `forceUpdate()`

**Comment by hongaar** [comment]
Hi, thanks for reporting this.
- Do you see any errors in your console?
- What happens if you replace
```
const relationships = this.dataStore.schema.models[operation.record.type].relationships
```

with
```
const relationships = this.dataStore.schema.models[operation.record.type].relationships || {}
```
?

**Comment by maksimsemenov** [comment]
No there were no any errors in console.

I tried to wrap an `Object.keys(relationships)...` call in `if (relationships )` statement and it worked fine

**Comment by hongaar** [comment]
Hi @maksimsemenov, did https://github.com/exivity/react-orbitjs/pull/13 fix your issue?

**Comment by maksimsemenov** [comment]
Hey @hongaar, I'm sorry but I ended up using some custom storage rather than orbit, so I can not check/confirm that #13 fixed the issue.

**Comment by hongaar** [comment]
No worries, I'll close this issue then.
