### ISSUE TITLE
Undefined prop

### ISSUE THREAD

**Issue by morgler** [exivity/react-orbitjs#2]
Awesome that you started this project! Before I tried to hook up orbitjs manually.

I cannot seem to get the props mapping to work. I simply map one query to props:

```
const mapRecordsToProps = {
  bandsQuery: q => q.findRecords("bands"),
}
```

And then I try to use it in the render function:

```
<Async promise={bandsQuery} pending={<b>Waiting</b>} then={(bands) =>
        <i>{bands.count} Bands</i>
}/>
```

But in my view, the `bandsQuery` prop is `undefined`. Even if I look at `this.props` of my view component, I see `bandsQuery` as a prop, but its value is `undefined`. I'm probably misunderstanding how this is supposed to work. 

Btw: If I load the data in `componentWillMount` via the injected queryStore prop, everything works fine (I get a promise which is then resolved).

**Comment by morgler** [comment]
Never mind – it was a stupid error on my side. Everything works fine without Async.

I had the wrong query (with a plural instead of the singular model name)

**Comment by hongaar** [comment]
Hi, thanks for opening an issue here. Docs is a little in 'bare minimum' state atm, at the moment, hope to extend it in the near future. As you probably figured out, the `mapRecordsToProps` returns records from the cache, so you don't need to wait for a promise to resolve.

Feel free to open an issue here or start a conversation on [Gitter](https://gitter.im/react-orbitjs/Lobby) if you have any more questions.
