### ISSUE TITLE
Bug: props mapRecordsToProps are not updated when returning empty object

### ISSUE THREAD

**Issue by Michiel87** [exivity/react-orbitjs#20]
```
const mapRecordsToProps = ({ type, id }) => {
    if (id) {
      return { record: q => q.findRecord({ type, id }) }
    }

    return {}
  }
```

If initially provided with id, record is found and passed to props. If subsequently no id is provided and we return an empty object, the record prop remains intact as is.

**Comment by hongaar** [comment]
@Michiel87 fixed in https://www.npmjs.com/package/react-orbitjs/v/0.1.12
