### ISSUE TITLE
Enhancement: Ability to return anything apart from just a record function

### ISSUE THREAD

**Issue by Michiel87** [exivity/react-orbitjs#21]
Lets say I use several functions to retrieve multiple types of records. Some of them conditionally. In this case it would be nice if I can return something else then a function based on the condition.

```
const mapRecordsToProps = ({ type, id }) => {
   return { 
      record: id ? q => q.findRecord({ type, id }) : {}, 
      account: q => q.findRecords('accounts'), 
   }
}
```

**Comment by hongaar** [comment]
I think the current functionality makes sense (always return an object with QueryExpression values) but it wouldn't hurt to sanity the returned object and omit all falsy values from it. Then you could do something like this:

```
const mapRecordsToProps = ({ type, id }) => ({ 
  record: id && q => q.findRecord({ type, id }), 
})
```

In the meantime, you could achieve the same using:

```
const mapRecordsToProps = ({ type, id }) => ({ 
  ...(id ? { record: q.findRecord({ type, id }) } : {})
})
```

But of course both these options would just omit the record from the resulting props, not set it to some default value.
