### ISSUE TITLE
Ability to use with function components?

### ISSUE THREAD

**Issue by bradjones1** [exivity/react-orbitjs#212]
I'm not the world's greatest React developer, but it seems to me that this is only compatible with class components? The closest analog I can find is React Context, which does [provide a wrapper component for use with function components](https://reactjs.org/docs/context.html#contextconsumer). Anything similar to that possible, here?

**Comment by hongaar** [comment]
Hi @bradjones1, thanks for raising this issue. This package is not actively developed (anymore) but it should be possible to use the `withData` function with React function components. Let me know if you experience problems with this approach and if possible, provide a codesandbox of the code you tried.

**Comment by bradjones1** [comment]
You're right, this is just my inexperience speaking. Thanks for the reply.

**Comment by hongaar** [comment]
NP!
