### ISSUE TITLE
Huge performance problem with lots of subscriptions

### ISSUE THREAD

**Issue by NullVoxPopuli** [exivity/react-orbitjs#25]
I've been digging through the handleTransform code in withData, and it seems like when a record changes, is added / removed, etc,
all HoC's watching the _type_ of object are re-rendered.

So, for example in: https://github.com/sillsdev/appbuilder-portal/
I have a user management table, and I can (re)assign roles/groups for permission reasons.
If I change a role on a user that isn't me, I would expect that the list of userRoles (join model) is updated for just that user. 

what I'm experiencing is that, all components subscribing to userRoles, are updated, so this includes my withCurrentUser Hoc, which is used everywhere.

Making this simple change to a user that isn't the current user causes 200+ dom updates by default.
I'm tweaking things atm, and exploring options.
I'll update this issue as I make discoveries

**Comment by hongaar** [comment]
That's correct, this lib is not smart enough to keep tabs on which subscription is consuming which _exact_ records, so it can't make educated guesses on which components to send new props to.

So your observation is correct: for any incoming transform, react-orbitjs will reconstruct the props for instances consuming record types included in the transform (it only tries to keep references intact for queries in the mapRecordToProps not affected by the transform).

**Comment by NullVoxPopuli** [comment]
I have a fork over at https://github.com/developertown/react-orbitjs where I was just able to get a many-to-many relationship change down from causing 250 dom updates (using the react profiler) down to 17.

Are you interested in a PR? 
I changed a lot :-/
diff: https://github.com/developertown/react-orbitjs/pull/8

**Comment by hongaar** [comment]
Sounds like a huge performance increase, can you provide a simple test case to test this difference in both branches?

As for the PR, there's too much going on to confidently merge this, I hope you understand. Even though the library is not very widely spread, I can't reliably assess how it would affect existing implementations.

Do you see any chance to break the PR down into smaller logical parts to see how this repo can benefit from your fork?

**Comment by NullVoxPopuli** [comment]
>  can you provide a simple test case to test this difference in both branches?

I wish I could -- I have no idea how to have automated tests for DOM updates in react -- I've just been using the react profiler from the browser dev tools.

> As for the PR, there's too much going on to confidently merge this, I hope you understand. Even though the library is not very widely spread, I can't reliably assess how it would affect existing implementations.

I totally understand! One of the ways I'll know I'm done working on the fork is if the test suite at https://github.com/sillsdev/appbuilder-portal/ still passes. Though, I have added a couple acceptance-level tests to help with overall usage testing.  I've been thinking about testing for these kinds of libraries a bit lately. Have you seen what ember-data is doing? where they have some scripts to run other people's projects against whatever commit? 
The external partner tests: https://travis-ci.org/emberjs/data
They don't release a version of ember-data unless all of those pass (afaik).
I think that adherance to non-breaking / quality control is really admirable.
Do you think this is something we could coordinate on to better assess breaking vs nonbreaking changes?

> Do you see any chance to break the PR down into smaller logical parts to see how this repo can benefit from your fork?

I do, but I'm afraid I don't have the time to do so -- I'm doing client work at the moment, and unless I get some R&D time post-client engagement, idk if it'll happen :(

**Comment by NullVoxPopuli** [comment]
@hongaar I've resolved performance issues in this fork: https://github.com/developertown/react-orbitjs

it has "external partner tests": https://travis-ci.com/developertown/react-orbitjs
So, if you're open to a giant code review, we could go through this and see what's different, what needs to be pulled in, etc.
also, maybe adding additional external partner tests would be good, too -- this ensures that changes to the library don't cause apps that use the library to break.

**Comment by hongaar** [comment]
Your fork looks very interesting. Would be happy to merge improvements in these areas:

- TS conversion
- Performance enhancements
- Hooks
- Build improvements (TS cli would already solve some/all issues)
- Test improvements (e.g. external partner tests, performance benchmarks, etc.)

Do you think it'd be possible to extract these things from your fork?

I have to think about this a bit more, but maybe we could continue a TS/hook only version of react-orbitjs in a `next` branch and get rid of hocs altogether?

**Comment by NullVoxPopuli** [comment]
> Do you think it'd be possible to extract these things from your fork?

unsure, I kinda rewrote everything. There were some things that are kinda similar, namely the transform listener, but that's it. :-\

> I have to think about this a bit more, but maybe we could continue a TS/hook only version of react-orbitjs

having a hook only version would be cool, but the external partner test (SIL) relies on the existence of higher-order components... _but_, we could reduce a lot of duplication by just re-implementing the higher-order components by using the hooks.

**Comment by hongaar** [comment]
For the record: #36 might help a little bit with this issue, even though it still doesn't implement a record-level filter.

**Comment by hongaar** [comment]
Going to close this now. The fork still looks very interesting but I don't have time atm to review/support these amount of changes. If someone is still interested in moving this project forward, I'd be happy to invite some maintainers to work on a new release in this repo.
