### ISSUE TITLE
Change mapRecordsToProps to use `store.query` by default.

### ISSUE THREAD

**Issue by hongaar** [exivity/react-orbitjs#4]
[As discussed on Gitter](https://gitter.im/orbitjs/orbit.js?at=5a3f628b232e79134d87d200):

Support both live and cache queries with something like this:

```javascript
const mapRecordsToProps = {
  moons: q => q.findRecords("moon"), // Uses store.query by default, or store.cache.query if DataProvider.props.cached is set to true
  planets: {cached: q => q.findRecords("planet")},
  asteroids: {live: q => q.findRecords("asteroid")},
}
```

Add new prop to `DataProvider` (defaults to false):
```jsx
<DataProvider dataStore={store} cached={true}/>
```

**Comment by hongaar** [comment]
I'll start working on this soon in the [feature/async](https://github.com/exivity/react-orbitjs/tree/feature/async) branch.

**Comment by pixelwhip** [comment]
I like the idea of being able to switch between these but it seems to me that querying the cache by default is more performant. In my experience, react components can render many times per second as props change. Querying the store could flood the remote server with requests if unrelated props are changing often. It feels more manageable to manually query the store in componentDidMount() or componentWillReceiveProps().  Or maybe I'm just misunderstanding how this works under the hood.

**Comment by hongaar** [comment]
That's an interesting point. Currently, queries are only executed if any of their related record types receive a transform (i.e. by querying or updating the store directly).

Queries would also be executed if they depend on a components own props (i.e. the mapRecordsToProps is a function accepting a single `ownProps` argument). Unfortunately, there is no way of determining if a changed prop is actually used in the query builder, so they'd always be executed. For live queries this would indeed be undesired.

This approach would have to be changed for 'live' queries, suggestions welcome.

**Comment by morgler** [comment]
Hm, my naive thought was to still query the cache by default. But if the cache is empty or expired, I would expect it to automatically trigger a live query. The cache expiration would throttle the barrage of live queries.

Again, this is just a naive wish from someone starting to use orbitjs – I don't know if it makes sense or if there is a simple alternative to the above procedure.

**Comment by hongaar** [comment]
Closing this issue to focus this package solely on making Orbit.js 'reactive'. Adding the ability for live queries would introduce changes which may be better off in another package.

I'm still open for a proposal on how to add this in somehow in the future.
