### ISSUE TITLE
removeRecord not rerendering

### ISSUE THREAD

**Issue by CodingItWrong** [exivity/react-orbitjs#42]
I have a component displaying all resources of a given type. When I `addRecord` the component is rerendered with the new record added, but when I `removeRecord` the component is not rerendered.

I have a demo repo here: https://github.com/CodingItWrong/react-orbitjs-test

## Actual Behavior

Say I run it and add todos 1, 2, and 3. I will see the component update each time and ultimately show (in some sort order):

- 1
- 2
- 3

If I complete todo 2, calling `removeRecord`, the component is not rerendered: its function is not called, and the same todos display. (Logging confirms that the `removeRecord` update operation completes successfully.

But then, if I add a new todo 4, when that causes the component to rerender, the todo I removed no longer shows in the list:

- 1
- 3
- 4

## Expected Behavior

In the same way that `addRecord` causes a component to rerender, I would expect `removeRecord` would also cause it to rerender components that depend on the relevant data.

**Comment by hongaar** [comment]
Thanks for reporting this. This issue has been open for a long time and unfortunately, I haven't been able to look at this. If it's still an issue, please comment below and I will reopen this issue.
