### ISSUE TITLE
Props don't update when Minified

### ISSUE THREAD

**Issue by pixelwhip** [exivity/react-orbitjs#6]
I'm still digging into this trying to figure out what the exact problem is, but thought I'd post an issue in case someone else runs into this.

I have a coordinator setup to use a remote JSON API source. It works as expected when not minified. When I minify a production build of my app using babel-minify-webpack-plugin, my component does not update. The request for the remote resource is still fired and has the correct response, but the component does not update its props.

My component looks like this 
```
class LocationsList extends Component {
  state = {};

  componentDidMount() {
    interceptClient.store.query(q => q.findRecords('node--location'));
  }

  render() {
    const locations = this.props.locations
      ? this.props.locations.map(location => <p key={location.id}>{location.attributes.title}</p>)
      : <p>No locations have been loaded.</p>;

    return (
      <div className="locationsList">
        {locations}
      </div>
    );
  }
}

const mapRecordsToProps = (ownProps) => {
  return {
    locations: q => q.findRecords("node--location").sort('title')
  }
}

LocationsList.propTypes = {
  locations: PropTypes.array.isRequired,
};

export default LocationsList = withData(mapRecordsToProps)(withStyles(styles)(LocationsList));
```

**Comment by hongaar** [comment]
Thanks for reporting this. Could you reproduce this behaviour on i.e. https://codesandbox.io/ ?

**Comment by pixelwhip** [comment]
I'm not sure how best to do that since this seems to be related to a minifying step in the build process. 

What I have found is that if I set the `deadcode` minify option to `false` in webpack, things work as expected.

In `webpack.config.js`
```
...
plugins: [
  new Minify({deadcode: false})
],
...
```
See https://github.com/babel/minify/tree/master/packages/babel-plugin-minify-dead-code-elimination.  I don't know what is being eliminated though.

**Comment by hongaar** [comment]
Can you trace back whether the bundled/main ([`dist/bundle/umd/react-orbitjs.js`](https://unpkg.com/react-orbitjs@0.1.6/dist/bundle/umd/react-orbitjs.js)) or the module/es ([`dist/module/es5/index.js`](https://unpkg.com/react-orbitjs@0.1.6/dist/module/es5/index.js)) version is used by the minifier?

I'm relatively new to this bundling/packaging game, and had some struggles with setting up the build configuration myself.

WebStorm seems to have problems properly detecting the imported code too, so it wouldn't surprise me if something is off in the dist versions of the library.

![image](https://user-images.githubusercontent.com/205834/36448938-7c8be826-1689-11e8-95eb-6ac5192f6384.png)

**Comment by hongaar** [comment]
@pixelwhip I'm doing some housecleaning. Still experiencing problems with this / any insight into what could be the cause?
