### ISSUE TITLE
example app?

### ISSUE THREAD

**Issue by NullVoxPopuli** [exivity/react-orbitjs#7]
I'm looking to use orbitjs for jsonapi, and am _very_ unclear on the interaction between the Store, the JSONAPISource, and coordinators.

Like, would I pass a coordinator to the DataProvider component?

**Comment by hongaar** [comment]
This is merely a 'bridge' library to use Orbit.js within a React app. To get a better understanding how to get Orbit.js up and running, their [getting started guide](http://orbitjs.com/v0.15/guide/getting-started.html) may help you.

Then, to use Orbit.js in your React app, you'd only need to pass to the `DataProvider` the instance of `store` you created with code like this:

```jsx
import { Schema } from '@orbit/data'
import Store from '@orbit/store'

const schema = new Schema({ ... })
const store = new Store({ schema })

// then
<DataProvider dataStore={store}>
  <MyApp/>
</DataProvider>
```
